nklayman/vue-cli-plugin-electron-builder

__tests__/commands.spec.js, generator/template/src/background.js, index.js
I refactored the code to give 2 seconds to the child process to handle exiting by itself when we restart it, on SIGINT/SIGTERM and when Ctrl+C is used on Windows.
Fixes #108
=> Kill Electron process gracefully during development

__tests__/commands.spec.js, generator/template/src/background.js, index.js
The IPC is useful on Windows to gracefully kill the child process but unnecessary on other platforms where signals can be used.
This code uses SIGTERM instead of the IPC on these platforms.
Tests are updated. I did not check the code styling (it looks consistent to me).
Fixes #117
=> Fix IPC-related issue on non-Windows platforms

package.json, yarn.lock
upgrade `vue` and `vue-template-compiler` to `2.5.20`, as `2.5.19` is broken.
=> chore(package): upgrade deps

index.d.ts
Since the code has a default blank object literal, the type definition should allow for no parameter to be passed.
=> Options param in testWithSpectron type definition should be optional

index.d.ts
Fixes a couple issues with the `stopServe` typedef
* JSDoc types can only be used inside documentation comments.ts(8020)
and 
* Generic type 'Promise<T>' requires 1 type argument(s).ts(2314)
=> Additional typescript definition fixes

__tests__/commands.spec.js, index.js
This fixes an issue where the background child process would emit the `exit` event and the `server:electron` would terminate unexpectedly after a restart following a file change (using folder watching, I didn't test using file watching).
=> fix(serve): refactor child process exit

__tests__/webpackConfig.spec.js, lib/webpackConfig.js
The change to allow package subpaths introduced a regex which is too broad, and maps packages like `express` to `express-ws`, causing `express` to not be listed in externals. This PR fixes that while still allowing subpaths.
=> fix(externals): handle package names that are substrings of externals list

index.d.ts
This fixes annoying error from `tsc`
=> fix(testWithSpectron): spectron implicitly has 'any' type

ui.js
On some Linux distributions the `electron:serve` task won't work without the `--no-sandbox` flag. 
see: 
https://github.com/electron/electron/issues/18265
https://github.com/electron/electron/issues/15760
https://github.com/electron/electron/issues/17972
=> feat(ui/serve): add --no-sandbox option

docs/guide/recipes.md
It quite tricky to build for many or other platforms other than the current one, especially with npm and the double dashes. 
Hopefully these instructions will save someone's time
=> Added instructions for multi platform build

lib/webpackConfig.js
When starting the server, an error occurs if the electron packet is not placed in the dependencies
=> fix(webpackConfig): get electron version from deps or devDeps

index.js
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/8b20b57fcb1910e75c23963eaadca8e79cf33938/index.js#L160-L164
If `pkg.dependencies` is `undefined` build failed with error:
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at \node_modules\vue-cli-plugin-electron-builder\index.js:156:16
```
=> fix(build): support package.json without 'dependencies' field

docs/guide/recipes.md
While `yarn electron:build` is an alias for `yarn run electron:build`, `npm electron:build` is **not** an alias for `npm run electron:build`.
=> docs(recipes): Updated multi platform build npm script

docs/guide/testingAndDebugging.md
Add missing commas in `testingAndDebugging` example.
=> docs(testingAndDebugging): fix config argument example

lib/testWithSpectron.js
Summary: Allow missing trailing slash in URL regex (both ```http://localhost:8081/``` and ```http://localhost:8081``` should be accepted).
I encountered this issue after setting my webpack's devServer to the following:
```
devServer: {
host: "localhost",
public: "localhost:8081",
disableHostCheck: true
}
```
Although this can easily be solved by adding a '/' to  ```devServer.public```, finding out that this was an issue was a real headache, because I would only receive a timeout in tests.
=> Update URL regex to allow missing trailing slash

docs/guide/configuration.md, index.js
I'm building multiple platforms where `src/main.js` isn't a reasonable default for me. I have my electron entrypoints in `src/platforms/desktop/main|background.ts`
This enables configuration of main and render process files, and adds documentation for for the new option. Hopefully this helps others as well!
=> feat(build, serve): custom renderer entry

lib/createProtocol.js
When using `instantiateStreaming`, the server needs to return the correct MIME type (`application/wasm`), otherwise the WASM instantiation will fail.
In the long term I think it would be beneficial to change the `createProtocol` function and accept a second argument, which can be used to specify custom MIME types for extensions without the need to modify the `createProtocol` function itself.
=> feat(build): support WASM mime type

lib/webpackConfig.js
Optional dependencies from package.json ended up being webpack'd even if specified in `externals`.
=> fix(webpackConfig): externalize optional dependencies

lib/createProtocol.js
registerBufferProtocol is now synchronous as of Electron 7  and the final callback argument is deprecated.
See: https://github.com/electron/electron/blob/7-0-x/docs/api/breaking-changes-ns.md
This fixes the warnings:
`ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.`
=> fix(createProtocol): ProtocolDeprecateCallback

__tests__/commands.spec.js, index.js
Adding functionality to include a `--skipElectronBuilder` flag to allow for bundle process to complete without having to fully build an executable.  This would allow developers/maintainers to have custom build/packaging solutions outside of the currently prescribed process in this plugin.
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1161
=> feat(build): add arg to skip electron-builder

index.js
Package `@vue/cli-service` and some other packages using `!process.env.VUE_CLI_MODERN_BUILD` for modern build check, so empty string `''` should be used instead of `false`.
This fixes browser version check and maybe some other features when building legacy app.
=> fix(build): legacy build browser version check

__tests__/commands.spec.js, index.js
Hi,
Thanks for you work.
The second argument is the replacer, the third the number of spaces:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
=> fix(build): Format properly generated package.json

index.d.ts, package.json
Hi, 
I use a vue.config.ts file to have type checking and autocompletion in my config.
So I added the types of the plugin config in this PR.
I may have missed some of them, I've just dug in the doc to find all the config keys and their type. (It might be handy to write this object in the doc, and add comments).
Thanks for your amazing work on this plugin.
=> chore(types): add plugin options

index.d.ts
Today, the `options` is optional, but only it. It means that if you want to set one option property, you have to set them all (in *TypeScript*).
For example, I commented out the `spectronOptions` property, and I get an error because it is missing:
```bash
test/e2e/specs/launch.spec.ts:28:64 - error TS2345: Argument of type '{ noSpectron: false; noStart: false; forceDev: false; mode: string; }' is not assignable to parameter of type 'Options'.
Property 'spectronOptions' is missing in type '{ noSpectron: false; noStart: false; forceDev: false; mode: string; }' but required in type 'Options'.
28     ({ app, stopServe, stdout } = await testWithSpectron(appi, {
~
29       noSpectron: false,
~~~~~~~~~~~~~~~~~~~~~~~~
... 
33       // spectronOptions: {}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
34     })); …
```
=> fix(testWithSpectron): options type should be Partial<>

docs/guide/guide.md
Yarn workspaces are broken-by-default
This provides instructions to get them working nicely
=> feat(docs/guide): add instructions for yarn workspaces

lib/webpackConfig.js
In the 3.0.0-alpha.3 release the entire if statement was commented out. That resulted in the mocha test not running. By uncommenting the code and updating it to PlayWright I got my mocha tests running.
I can't find the code being commented out on the v3 branch, but please make sure it isn't commented out.
=> Update testWithSpectron to testWithPlaywright

docs/guide/recipes.md
`set GH_TOKEN=TOKEN-GOES-HERE` does not work in powershell. So, I added the instruction.
=> Added powershell GH_TOKEN environment variable instruction
